name: Update Events Page

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install jq

      - name: Fetch Events from Airtable
        run: |
          curl -X GET "https://api.airtable.com/v0/YOUR_BASE_ID/event_deets" \
          -H "Authorization: Bearer ${{ secrets.AIRTABLE_API_KEY }}" > events.json

      - name: Generate HTML from JSON
        run: |
          echo '<h2>Upcoming Events</h2><div id="upcoming-events"></div>' > events.html
          echo '<h2>Previous Events</h2><div id="previous-events"></div>' >> events.html
          
          jq -r '
          .records[] | 
          "<div class=\"event_deets\">
          <h3>" + (.fields."Event Name" // "") + "</h3>
          <p>" + (if .fields."Event Start Date" then (.fields."Event Start Date" | fromdate | strftime("%A %B %d %Y %I:%M %p")) else "" end) + " until " +
          (if .fields."Event End Date" then (.fields."Event End Date" | fromdate | strftime("%I:%M %p")) else "" end) + "</p>
          <button class=\"toggle-btn\" onclick=\"toggleDescription(this)\">Show Details</button>
          " + (if .fields."Event Description" then "<div class=\"event_description\" style=\"display: none;\"><p>" + .fields."Event Description" + "</p></div>" else "" end) + "
          " + 
          (if .fields."Event URL" and .fields."Facebook URL" then "<a href=\"" + .fields."Event URL" + "\">Event Link</a> | <a href=\"" + .fields."Facebook URL" + "\">Facebook link</a>" 
          else if .fields."Event URL" then "<a href=\"" + .fields."Event URL" + "\">Event Link</a>"
          else if .fields."Facebook URL" then "<a href=\"" + .fields."Facebook URL" + "\">Facebook link</a>"
          else "" end) + 
          "</div>"
          ' events.json >> events.html

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add events.html
          git commit -m "Auto-update events page with latest Airtable data" || echo "No changes to commit"
          git push
