name: Update Events Page

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install jq

      - name: Fetch Events from Airtable
        run: |
          echo "📢 Fetching data from Airtable..."
          curl -X GET "https://api.airtable.com/v0/appT25NC13v3OxP1O/event_deets" \
          -H "Authorization: Bearer ${{ secrets.AIRTABLE_API_KEY }}" > events.json

      - name: Debug Airtable API Response
        run: |
          echo "📢 Checking Airtable API response..."
          cat events.json
          echo "✅ API response printed above."

      - name: Validate API Response
        run: |
          if jq -e '.records' events.json >/dev/null; then
            echo "✅ API response contains records."
          else
            echo "❌ ERROR: API response does not contain valid records."
            exit 1
          fi

      - name: Update Events Sections in HTML
        run: |
          # Extract header (content before the first <h2>Upcoming Events</h2>)
          awk '/<h2>Upcoming Events<\/h2>/{exit} {print}' events.html > header.html
          
          # Extract footer (content after </div> of previous-events section)
          tac events.html | awk '/<h2>Previous Events<\/h2>/{p=1; next} p' | tac > footer.html
          
          # Start the new updated events section
          echo '<h2>Upcoming Events</h2><div id="upcoming-events">' > events-content.html
          
          # Generate upcoming events from JSON
          jq -r '
          if .records then
            .records[]
            | select(.fields.status != "Preliminary")  # Filters out events with status = Preliminary
            | select(.fields."Event Start Date" | fromdate? >= now)  # Upcoming events only
            | "<div class=\"event_deets\">
              <h3>" + (.fields."Event Name" // "Untitled Event") + "</h3>
              <p>" + 
                (if .fields."Event Start Date" then (.fields."Event Start Date" | fromdate? | strftime("%A %B %d %Y %I:%M %p")) else "TBD" end) + 
                " until " +
                (if .fields."Event End Date" then (.fields."Event End Date" | fromdate? | strftime("%I:%M %p")) else "TBD" end) + 
              "</p>
              <button class=\"toggle-btn\" onclick=\"toggleDescription(this)\">Show Details</button>" +
              (if .fields."Event Description" then 
                "<div class=\"event_description\" style=\"display: none;\"><p>" + .fields."Event Description" + "</p></div>" 
              else 
                "" 
              end) + 
              (if .fields."Event URL" and .fields."Facebook URL" then 
                "<a href=\"" + .fields."Event URL" + "\">Event Link</a> | <a href=\"" + .fields."Facebook URL" + "\">Facebook link</a>" 
              elif .fields."Event URL" then 
                "<a href=\"" + .fields."Event URL" + "\">Event Link</a>" 
              elif .fields."Facebook URL" then 
                "<a href=\"" + .fields."Facebook URL" + "\">Facebook link</a>" 
              else 
                "" 
              end) + 
              "</div>"
          else
            "Error: No records found."
          end
          ' events.json >> events-content.html

          # Close upcoming events section
          echo '</div>' >> events-content.html
          
          # Start previous events section
          echo '<h2>Previous Events</h2><div id="previous-events">' >> events-content.html
          
          # Generate previous events from JSON (older events)
          jq -r '
          if .records then
            .records[]
            | select(.fields.status != "Preliminary")  # Filters out Preliminary events
            | select(.fields."Event Start Date" | fromdate? < now)  # Ensures event is in the past
            | "<div class=\"event_deets\">
              <h3>" + (.fields."Event Name" // "Untitled Event") + "</h3>
              <p>" + 
                (if .fields."Event Start Date" then (.fields."Event Start Date" | fromdate? | strftime("%A %B %d %Y %I:%M %p")) else "TBD" end) + 
                " until " +
                (if .fields."Event End Date" then (.fields."Event End Date" | fromdate? | strftime("%I:%M %p")) else "TBD" end) + 
              "</p>
              <button class=\"toggle-btn\" onclick=\"toggleDescription(this)\">Show Details</button>" +
              (if .fields."Event Description" then 
                "<div class=\"event_description\" style=\"display: none;\"><p>" + .fields."Event Description" + "</p></div>" 
              else 
                "" 
              end) + 
              (if .fields."Event URL" and .fields."Facebook URL" then 
                "<a href=\"" + .fields."Event URL" + "\">Event Link</a> | <a href=\"" + .fields."Facebook URL" + "\">Facebook link</a>" 
              elif .fields."Event URL" then 
                "<a href=\"" + .fields."Event URL" + "\">Event Link</a>" 
              elif .fields."Facebook URL" then 
                "<a href=\"" + .fields."Facebook URL" + "\">Facebook link</a>" 
              else 
                "" 
              end) + 
              "</div>"
          else
            "Error: No records found."
          end
          ' events.json >> events-content.html

          # Close previous events section
          echo '</div>' >> events-content.html

          # Combine header, updated events content, and footer into final events.html
          cat header.html events-content.html footer.html > events.html

          # Cleanup temporary files
          rm header.html footer.html events-content.html

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add events.html
          git commit -m "Auto-update events page with latest Airtable data" || exit 0
          git push origin main
